<a href="https://colab.research.google.com/github/ibrahimfakhrey/AMS/blob/main/start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
s=tf.constant([[10,20],[20,10]])
s

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 10]], dtype=int32)>

In [ ]:
s.ndim

2

In [ ]:
changable=tf.Variable([10,7])
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
changable[0].assign(7)
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
r_1=tf.random.Generator.from_seed(7)
r_1=r_1.normal(shape=(3,2))
r_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [ ]:
r_2=tf.random.Generator.from_seed(7)
r_2=r_2.normal(shape=(3,2))
r_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [ ]:
not_shuffle=tf.constant([[10,7],
                         [3,4],
                         [2,5]

])
tf.random.shuffle(not_shuffle,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a=tf.constant(numpy_A,shape=(2,3,4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("datatype",rank_4_tensor.dtype)
print("number",rank_4_tensor.ndim)
print("shape",rank_4_tensor.shape)
print("size",tf.size(rank_4_tensor).numpy())

datatype <dtype: 'float32'>
number 4
shape (2, 3, 4, 5)
size 120


In [ ]:
r = tf.random.Generator.from_seed(7)

# Generate random numbers from a normal distribution with the specified shape
random_numbers = r.normal(shape=(3, 2))

# Shuffle the random numbers
shuffled_numbers = tf.random.shuffle(random_numbers, seed=42)

print(shuffled_numbers)

tf.Tensor(
[[ 0.69211644  0.84215707]
 [-0.8757901  -0.08857018]
 [-1.3240396   0.28785667]], shape=(3, 2), dtype=float32)


In [ ]:
# prompt: great example to tensor and add dimension to it

import tensorflow as tf

# Create a 1-dimensional tensor
tensor = tf.constant([1, 2, 3])

# Add a new dimension to the tensor using tf.expand_dims
expanded_tensor = tf.expand_dims(tensor, axis=1)

# Print the original and expanded tensors
print("Original tensor:", tensor)
print("Expanded tensor:", expanded_tensor)


Original tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Expanded tensor: tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [ ]:
import tensorflow as tf


# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
X ,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.matmul(X, tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.transpose(Y).shape

TensorShape([2, 3])

In [ ]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
X.shape ,Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
z=tf.constant([[1, 2,3,5],
                 [3, 4,3,5],
                 [5, 6,3,5]])
w=tf.constant([[1, 2,5],
                 [3, 4,5],
                 [5, 6,5]])
z.shape,w.shape

(TensorShape([3, 4]), TensorShape([3, 3]))

In [ ]:
tf.transpose(w) @z

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[35, 44, 27, 45],
       [44, 56, 36, 60],
       [45, 60, 45, 75]], dtype=int32)>

In [ ]:
import tensorflow as tf


# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X @ tf.reshape(Y,shape=(2,3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [4]:
import numpy as np
r=tf.constant(np.random.randint(0,100,size=50))

In [5]:
r

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 25, 26, 70, 58, 74, 93,  9, 72,  3, 38,  6, 60, 71, 16, 66, 28,
       92, 31, 93, 66, 11, 45, 77, 16, 54, 53, 35, 87, 23, 47, 99, 56, 89,
       17, 10,  3, 17, 48, 81, 28, 18, 78, 80, 49, 19, 53, 10, 59, 60])>

In [7]:
tf.reduce_min(r)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [9]:
tf.reduce_max(r)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [10]:
tf.reduce_mean(r)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [11]:
tf.abs(r)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 25, 26, 70, 58, 74, 93,  9, 72,  3, 38,  6, 60, 71, 16, 66, 28,
       92, 31, 93, 66, 11, 45, 77, 16, 54, 53, 35, 87, 23, 47, 99, 56, 89,
       17, 10,  3, 17, 48, 81, 28, 18, 78, 80, 49, 19, 53, 10, 59, 60])>

In [12]:
tf.reduce_sum(r)

<tf.Tensor: shape=(), dtype=int64, numpy=2404>

In [17]:
import tensorflow_probability as tfp

tfp.stats.variance(r)

<tf.Tensor: shape=(), dtype=int64, numpy=817>

In [21]:
new=tf.random.uniform(shape=[50])
new

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.27394426, 0.24808693, 0.45575845, 0.6827853 , 0.84998405,
       0.05367458, 0.12202835, 0.3471911 , 0.41027677, 0.01278734,
       0.3818314 , 0.12692034, 0.7810432 , 0.4624139 , 0.97253406,
       0.89025605, 0.2976644 , 0.26324928, 0.6663618 , 0.31720424,
       0.86634827, 0.12227476, 0.30180693, 0.47138238, 0.03280747,
       0.8996701 , 0.188465  , 0.7989043 , 0.37814856, 0.15494978,
       0.4953766 , 0.07463241, 0.49531198, 0.8077235 , 0.6350515 ,
       0.20314789, 0.03805697, 0.8163482 , 0.8153448 , 0.7124162 ,
       0.27574372, 0.4595796 , 0.28149605, 0.6285459 , 0.8763336 ,
       0.8513986 , 0.930506  , 0.5214621 , 0.3238305 , 0.09568584],
      dtype=float32)>

In [22]:
tf.argmax(new)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [23]:
new[tf.argmin(new)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.012787342>

In [25]:
some_list=[0,1,2,3,4]
tf.one_hot(some_list,depth=5,on_value="green",off_value="red")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'green', b'red', b'red', b'red', b'red'],
       [b'red', b'green', b'red', b'red', b'red'],
       [b'red', b'red', b'green', b'red', b'red'],
       [b'red', b'red', b'red', b'green', b'red'],
       [b'red', b'red', b'red', b'red', b'green']], dtype=object)>

In [27]:
ra=tf.constant(np.random.randint(0,1,size=[3,500]))
ra

<tf.Tensor: shape=(3, 500), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>

In [29]:
second=tf.random.uniform(shape=[5,300])
second

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.4633    , 0.39895606, 0.2768935 , ..., 0.7542082 , 0.43991852,
        0.9380537 ],
       [0.3762325 , 0.91095674, 0.6629844 , ..., 0.5723835 , 0.30483258,
        0.34059918],
       [0.28684223, 0.39223218, 0.9993231 , ..., 0.40152514, 0.1443193 ,
        0.71311283],
       [0.02919531, 0.04976952, 0.08997536, ..., 0.4520533 , 0.3487041 ,
        0.8994063 ],
       [0.46963155, 0.1597178 , 0.7452457 , ..., 0.34794164, 0.0693363 ,
        0.2693869 ]], dtype=float32)>

In [30]:
third=tf.random.uniform(shape=[5,300])

In [31]:
second @ third

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [5,300], In[1]: [5,300] [Op:MatMul] name: 

In [32]:
second @ tf.transpose(third)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.81613 , 77.01495 , 71.71501 , 75.7377  , 72.03529 ],
       [75.742546, 76.125725, 73.356995, 75.46025 , 78.621124],
       [73.63908 , 74.206314, 71.574234, 73.4806  , 73.415215],
       [79.608925, 79.15279 , 75.97212 , 78.03901 , 80.30357 ],
       [71.54407 , 74.829834, 71.862274, 74.20404 , 75.452866]],
      dtype=float32)>

In [35]:
tf.tensordot(tf.transpose(third),second, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.5586612 , 0.5719794 , 1.0976871 , ..., 0.9128636 , 0.46987334,
        1.2797539 ],
       [1.0655092 , 1.4608479 , 1.9693553 , ..., 1.5833267 , 0.787819  ,
        1.8466686 ],
       [1.0450324 , 1.2116971 , 1.9074174 , ..., 1.7028046 , 0.88797635,
        2.3087258 ],
       ...,
       [0.91995144, 0.8672574 , 1.3988663 , ..., 1.2419841 , 0.59582055,
        1.5132973 ],
       [1.3500762 , 1.5037318 , 2.309175  , ..., 2.1287386 , 1.1053805 ,
        2.7633476 ],
       [0.9102325 , 1.2451842 , 1.3601754 , ..., 1.4810731 , 0.81098473,
        1.6342427 ]], dtype=float32)>

In [36]:
nn=tf.random.uniform(shape=[224, 224, 3])
nn

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[2.6859641e-01, 7.9126894e-01, 3.7114799e-01],
        [5.3606522e-01, 9.0883911e-01, 3.8814437e-01],
        [1.5408969e-01, 3.2032645e-01, 1.7776132e-02],
        ...,
        [2.4532890e-01, 9.5612681e-01, 9.5164573e-01],
        [1.2784505e-01, 5.5106401e-01, 9.7734642e-01],
        [8.4592271e-01, 7.3370016e-01, 9.6682978e-01]],

       [[5.0036275e-01, 1.9634271e-01, 7.6264143e-01],
        [2.9014814e-01, 9.3491590e-01, 6.7670000e-01],
        [6.6994727e-01, 6.6076541e-01, 5.2295196e-01],
        ...,
        [1.9737148e-01, 6.0025716e-01, 6.7596424e-01],
        [2.9008448e-01, 5.4743123e-01, 9.8403358e-01],
        [2.6022947e-01, 9.4183135e-01, 4.8580170e-03]],

       [[3.4724355e-02, 3.2103527e-01, 2.2387171e-01],
        [6.8989527e-01, 2.4438059e-01, 8.4474170e-01],
        [7.0006096e-01, 7.3810816e-03, 6.4364195e-02],
        ...,
        [1.0869002e-01, 8.4548986e-01, 9.8691142e-01],
        [7.2052908e-01

In [37]:
tf.reduce_max(nn)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999046>

In [38]:
tf.reduce_min(nn)

<tf.Tensor: shape=(), dtype=float32, numpy=1.1920929e-06>

In [39]:
tt=np.random.rand(1, 224, 224, 3)

In [40]:
tt

array([[[[0.11792917, 0.43202798, 0.89330111],
         [0.74166533, 0.40965581, 0.05089769],
         [0.27358083, 0.81870676, 0.07851004],
         ...,
         [0.30188556, 0.72175756, 0.15774415],
         [0.94586366, 0.0263762 , 0.85397346],
         [0.26621052, 0.52574753, 0.35580608]],

        [[0.44590491, 0.81236343, 0.22592668],
         [0.75149638, 0.17397856, 0.44158681],
         [0.87312499, 0.52827234, 0.79780836],
         ...,
         [0.32946522, 0.97391757, 0.88450306],
         [0.79688344, 0.50275956, 0.87312225],
         [0.37028827, 0.85414381, 0.24316223]],

        [[0.9405102 , 0.43870352, 0.85800394],
         [0.49312805, 0.44799505, 0.46935136],
         [0.05701204, 0.81399171, 0.24580404],
         ...,
         [0.23706224, 0.1231507 , 0.42980934],
         [0.508062  , 0.9222712 , 0.45447108],
         [0.98980934, 0.08880694, 0.49194477]],

        ...,

        [[0.44267605, 0.30276965, 0.36002963],
         [0.01130322, 0.17234827, 0.56308573]

In [43]:
np.squeeze(tt).shape

(224, 224, 3)